### ISSUE TITLE
Scene editor interactive fails to load

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#1659]
The scene editor interactive fails to load with the following error:

```
Uncaught TypeError: Cannot set properties of undefined (setting 'value')
    at init (scene-editor.js:97515:42)
    at Object.582.../../../js/third-party/threejs/Detector.js (scene-editor.js:97409:1)
    at o (scene-editor.js:1:265)
    at r (scene-editor.js:1:431)
    at scene-editor.js:1:460111
```

What is odd that it appears to fail with the same version it has previous worked with.

**Comment by Yamboy1** [comment]
The scene editor interactive now throws a different error

```
Uncaught Error: The global import function is not available anymore in v6.0.0. 
Please create a mathjs instance if you want to import functions. 
Example:

  import { create, all } from 'mathjs';
  const mathjs = create(all);
  mathjs.import(...);

    at Object.deprecatedImport [as import] (scene-editor.js:8724:11)
    at 1.../../../js/third-party/threejs/Detector.js (scene-editor.js:80:8)
    at o (scene-editor.js:1:265)
    at r (scene-editor.js:1:431)
    at scene-editor.js:1:1
```
