### ISSUE TITLE
getresponse() got an unexpected keyword argument 'buffering' error

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#370]
## Description

The following error sometimes occurs when running our tests on Travis-ci (for example: https://travis-ci.org/uccser/cs-field-guide/jobs/143705257).

```
Found existing image cache/math-image-1692558082a23c9cb45975032460d162bee3c5a4.png for nlog(n)
Found existing image cache/math-image-a0a0ecc4fa470e45995967b80a24950e78459583.png for n^2
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.5-dev/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/opt/python/3.5-dev/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.5-dev/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.5-dev/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/opt/python/3.5-dev/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.5-dev/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generateguide.py", line 680, in <module>
    main()
  File "generateguide.py", line 672, in main
    pdf_guide = Guide(generator_settings=generator_settings, guide_settings=guide_settings, language_code=language, version=version, output_type=PDF, html_generator=html_generator, html_templates=html_templates, translations=translations, regex_list=regex_list)
  File "generateguide.py", line 66, in __init__
    self.traverse_files(self.structure, getattr(self, "process_section"))
  File "generateguide.py", line 145, in traverse_files
    self.traverse_files(folder, process_file_function, index_page_first)
  File "generateguide.py", line 147, in traverse_files
    process_file_function(file)
  File "generateguide.py", line 177, in process_section
    file_node.section.parse_markdown_content(self.html_templates)
  File "/home/travis/build/uccser/cs-field-guide/generator/markdownsection.py", line 905, in parse_markdown_content
    text = re.sub(regex.expression, regex.function, text, flags=re.MULTILINE)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/travis/build/uccser/cs-field-guide/generator/markdownsection.py", line 238, in process_math_text
    image_filename = self.guide.print_renderer.render_math(equation)
  File "/home/travis/build/uccser/cs-field-guide/generator/print_media.py", line 22, in render_math
    request = requests.get( 'http://latex.codecogs.com/png.latex?\dpi{{120}} {formula}'.format(formula=formula))
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.5-dev/lib/python3.5/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

```

**Comment by JackMorganNZ** [comment]
This issue is appears a few times within the Python Requests Package issue tracker ([#1915](https://github.com/kennethreitz/requests/issues/1915) [#2510](https://github.com/kennethreitz/requests/issues/2510)) and may be caused by a read timeout. It may be worth testing a longer read timeout when making a request, details here: http://docs.python-requests.org/en/master/user/advanced/#timeouts.
