### ISSUE TITLE
Provide more information with Verto exceptions

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#605]
See example. This may require changes from Verto (haven't thought it through yet).

```
Added chapter: Coding - Compression
  Added chapter section: What's the big picture?
  Added chapter section: Run Length Encoding
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/docker_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/docker_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/docker_venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/docker_venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/cs-field-guide/csfieldguide/general/management/commands/updatedata.py", line 15, in handle
    management.call_command("loadchapters")
  File "/docker_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/docker_venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/cs-field-guide/csfieldguide/chapters/management/commands/loadchapters.py", line 74, in handle
    structure_filename=chapter_structure_file,
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/cs-field-guide/csfieldguide/chapters/management/commands/_ChaptersLoader.py", line 89, in load
    structure_filename=structure_filename
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/cs-field-guide/csfieldguide/chapters/management/commands/_ChapterSectionsLoader.py", line 61, in load
    content_translations = self.get_markdown_translations(content_filename)
  File "/cs-field-guide/csfieldguide/utils/TranslatableModelLoader.py", line 123, in get_markdown_translations
    **kwargs
  File "/cs-field-guide/csfieldguide/utils/BaseLoader.py", line 137, in convert_md_file
    result = self.converter.convert(content)
  File "/docker_venv/lib/python3.6/site-packages/verto/Verto.py", line 73, in convert
    html_string = self.converter.convert(text)
  File "/docker_venv/lib/python3.6/site-packages/markdown/__init__.py", line 371, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/docker_venv/lib/python3.6/site-packages/markdown/blockparser.py", line 65, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/docker_venv/lib/python3.6/site-packages/markdown/blockparser.py", line 80, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/docker_venv/lib/python3.6/site-packages/markdown/blockparser.py", line 98, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/docker_venv/lib/python3.6/site-packages/verto/processors/GenericTagBlockProcessor.py", line 60, in run
    argument_values = parse_arguments(self.processor, match.group('args'), self.arguments)
  File "/docker_venv/lib/python3.6/site-packages/verto/processors/utils.py", line 76, in parse_arguments
    raise ArgumentMissingError(processor, argument, '{} is a required argument.'.format(argument))
verto.errors.ArgumentMissingError.ArgumentMissingError: file-path is a required argument.
```

**Comment by JackMorganNZ** [comment]
In the `content-restructure` branch, the `BaseLoader` now catches all Verto errors:

```
  File "/cs-field-guide/csfieldguide/chapters/management/commands/_ChapterSectionsLoader.py", line 61, in load
    content_translations = self.get_markdown_translations(content_filename)
  File "/cs-field-guide/csfieldguide/utils/TranslatableModelLoader.py", line 123, in get_markdown_translations
    **kwargs
  File "/cs-field-guide/csfieldguide/utils/BaseLoader.py", line 139, in convert_md_file
    raise VertoConversionError(md_file_path, e) from e
utils.errors.VertoConversionError.VertoConversionError: 
****************************ERROR****************************
File: /cs-field-guide/csfieldguide/chapters/content/en/coding-encryption/sections/substitution-ciphers.md

Conversion of file /cs-field-guide/csfieldguide/chapters/content/en/coding-encryption/sections/substitution-ciphers.md failed with error: "Argument found but value not contained in double quotes."
```
