### ISSUE TITLE
Pixel Viewer Interactive displaying blank white image

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#878]
Browser: Firefox
URL: https://cs-field-guide-dev.appspot.com/en/interactives/pixel-viewer/

When loading the Pixel Viewer Interactive; the image is zoomed in on, then the menu fades in and simultaneously _the image fades to white_

Subsequently no interactions with the interactive beyond opening/closing the menu result in a visible change

![v](https://user-images.githubusercontent.com/25916475/53129475-8277ca80-35cc-11e9-8fd8-5a20fdbb9923.png)

This and issue #880 could be resolved together

**Comment by JackMorganNZ** [comment]
Error log:

```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at get_pixel_data (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:846:48)
    at paint (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:946:19)
    at Tiling.render (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/third-party/Tiling.js:110:4)
    at Scroller.render [as __callback] (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:912:12)
    at Scroller.__publish (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/third-party/Scroller.js:1123:11)
    at Scroller.scrollTo (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/third-party/Scroller.js:599:9)
    at Image.image.onload (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:869:18)
pixel-viewer.js:846 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at get_pixel_data (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:846:48)
    at paint (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:946:19)
    at Tiling.render (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/third-party/Tiling.js:110:4)
    at Scroller.render [as __callback] (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:912:12)
    at Scroller.__publish (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/third-party/Scroller.js:1123:11)
    at Scroller.scrollTo (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/third-party/Scroller.js:599:9)
    at Scroller.setDimensions (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/third-party/Scroller.js:309:9)
    at reflow (https://storage.googleapis.com/cs-field-guide-dev.appspot.com/static/interactives/pixel-viewer/js/pixel-viewer.js:984:14)
```

Seems to be a CORS issue.

**Comment by courtneycb** [comment]
Useful link https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

I think we need to set the origins allowed to '*' in the CORS configuratiomn file. Currently researching if this poses any security risks.

**Comment by courtneycb** [comment]
This is happening on all canvas objects. So will affect:
`image-bit-comparer`
`jpeg-compression.js`
`viola-jones`
(I think that is all)

We think the best solution at this stage is to add `https://storage.googleapis.com/cs-field-guide-dev.appspot.com/` and `https://storage.googleapis.com/csfieldguide.org.nz/` to the accepted origins.

**Comment by courtneycb** [comment]
^Above 'solution' didn't work :(

**Comment by eAlasdair** [comment]
#963 fixed Image Bit Comparer at least
